# Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
# 
# Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
# Pentagonal	Pn=n(3n−1)/2	1, 5, 12, 22, 35, ...
# Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
# It can be verified that T285 = P165 = H143 = 40755.
# 
# Find the next triangle number that is also pentagonal and hexagonal.

from figurate_numbers import *

# sanity check
for x in [triangular(285),triangular(286)]:
    print("{0},{1},{2},{3}".format(x, is_triangular(x), is_pentagonal(x), is_hexagonal(x)))

# start at t285, and go forward, finding the next number
n = 286
while True:
    x = triangular(n)
    # no need to call is_triangular: we just generated it, we know it is
    if is_pentagonal(x) and is_hexagonal(x):
        print(x)
        break
    n += 1