# for problems 044, 045, 061...
# Triangle, square, pentagonal, hexagonal, heptagonal, and octagonal numbers are all figurate (polygonal) numbers 
# and are generated by the following formulae:
#
# Triangle	 	P3,n=n(n+1)/2	 	1, 3, 6, 10, 15, ...
# Square	 	P4,n=n^2	     	1, 4, 9, 16, 25, ...
# Pentagonal	P5,n=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
# Hexagonal	 	P6,n=n(2n−1)	 	1, 6, 15, 28, 45, ...
# Heptagonal	P7,n=n(5n−3)/2	 	1, 7, 18, 34, 55, ...
# Octagonal	 	P8,n=n(3n−2)	 	1, 8, 21, 40, 65, ...

# took the formulae above, applied the quadratic formula, and derived the tests below
from math import sqrt, modf

def is_triangular(x):
    n = (sqrt(8*x + 1) - 1) / 2
    return modf(n)[0] == 0.0

def is_square(x):
    n = sqrt(x)
    return modf(n)[0] == 0.0

def is_pentagonal(x):
    n = (sqrt(24*x + 1) + 1) / 6
    return modf(n)[0] == 0.0

def is_hexagonal(x):
    n = (sqrt(8*x + 1) + 1) / 4
    return modf(n)[0] == 0.0

def is_heptagonal(x):
    n = (sqrt(40*x + 9) + 3) / 10
    return modf(n)[0] == 0.0

def is_octagonal(x):
    n = (sqrt(3*x + 1) + 1) / 3
    return modf(n)[0] == 0.0

def triangular(n):
    return int(n*(n+1)/2)